### Importing Pytorch

In [2]:
import torch
print(torch.__version__)

2.2.0


### Introduction to Tensors

#### Creating tensors

In [8]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [10]:
# Get python number within a tensor
scalar.item()

7

In [11]:
# Vector

vector = torch.tensor([7,1])
vector

tensor([7, 1])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [14]:
# Matrix

matrix = torch.tensor([[7,8], [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
matrix.ndim

2

In [16]:
matrix.shape

torch.Size([2, 2])

In [17]:
# Tensor
tensor = torch.tensor([[[1,2,3], [3,6,9], [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
tensor.ndim

3

In [19]:
tensor.shape

torch.Size([1, 3, 3])

#### Random tensors

In [22]:
# Create random tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.5009, 0.6854, 0.2907, 0.2891],
        [0.1330, 0.8284, 0.6521, 0.8369],
        [0.9879, 0.7965, 0.4813, 0.8944]])

In [24]:
# Image size random tensor of (224, 224, 3)

random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

#### Zeros and Ones

In [25]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [26]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

#### Creating a range and tensors like

In [30]:
zero_to_ten = torch.arange(0, 10, 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensor Datatypes

In [38]:
float32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float32_tensor.shape, float32_tensor.dtype, float32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [39]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

### Getting information from tensors

In [40]:
# Create a tensor
some_tensor = torch.rand(size=(3,4))

# Find details about it
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Dtype of tensor: {some_tensor.dtype}')
print(f'Device tensor is on: {some_tensor.device}')

Shape of tensor: torch.Size([3, 4])
Dtype of tensor: torch.float32
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

#### Basic operations

In [41]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [42]:
tensor * 10

tensor([10, 20, 30])

In [43]:
tensor -= 10
tensor

tensor([-9, -8, -7])

In [44]:
tensor += 10
tensor

tensor([1, 2, 3])

In [45]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [46]:
tensor * tensor

tensor([1, 4, 9])

#### Matrix Multiplication

In [47]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [48]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [49]:
tensor @ tensor

tensor(14)

In [51]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 374 µs, sys: 1.82 ms, total: 2.19 ms
Wall time: 5.48 ms


tensor(14)

In [52]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 86 µs, sys: 169 µs, total: 255 µs
Wall time: 162 µs


tensor(14)

### Most common errors in Deep Learning

In [55]:
# Shape mismatches
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]], dtype=torch.float32)
print(f'Shape of tensor A: {tensor_A.shape}\n Shape of tensor B: {tensor_B.shape}')
torch.matmul(tensor_A, tensor_B)

Shape of tensor A: torch.Size([3, 2])
 Shape of tensor B: torch.Size([3, 2])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [56]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [57]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

torch.Linear() is a feed forward layer which implements a matmul between an input x and weights matrix A:

y = x.A^T + b

y = output\
x = input to the layer\
A = weights matrix that updates over time\
b = bias term used to slighly offset weights and inputs

In [62]:
# Linear layer starts with a random weights matrix 
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
x = tensor_A
y = linear(x)
print(f'Input shape: {x.shape}')
print(f'Output shape: {y.shape}')

Input shape: torch.Size([3, 2])
Output shape: torch.Size([3, 6])


#### Finding min, max, mean, sum, etc (aggregation)

In [69]:
# Create a tensor
x = torch.arange(0, 100, 10, dtype=torch.float32)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [70]:
print(f'Minimum: {x.min()}')
print(f'Maximum: {x.max()}')
print(f'Mean: {x.mean()}')
print(f'Sum: {x.sum()}')

Minimum: 0.0
Maximum: 90.0
Mean: 45.0
Sum: 450.0


#### Positional min/max

In [71]:
print(f'Index where max occurs: {torch.argmax(x)}')
print(f'Index where min occurs: {torch.argmin(x)}')

Index where max occurs: 9
Index where min occurs: 0


#### Change tensor datatype

In [72]:
print(f'Current type of tensor: {x.dtype}')
x_16 = x.type(torch.float16)
print(f'New type of tensor: {x_16.dtype}')

Current type of tensor: torch.float32
New type of tensor: torch.float16


#### Reshaping, stacking, squeezing, and unsqueezing

In [75]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [80]:
# Add extra dimension
x_reshaped = x.reshape(shape=(1,7))
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [83]:
# Change view
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [84]:
# Changing view changes x (original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [87]:
# Stack
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [88]:
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Squeeze
x_squeezed = x_reshaped.squeeze()
print(f'New tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])
New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [89]:
# Unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f'New tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [92]:
# Permute (changing value in permute changes in original as well)
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1) # 2->0, 0->1, 1->2
print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}')

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

In [99]:
x = torch.arange(1, 19).reshape(2, 3, 3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [100]:
# Indexing bracket by bracket
print(f'First bracket: {x[0]}')
print(f'Second bracket: {x[0][0]}')
print(f'Third bracket: {x[0][0][0]}')

First bracket: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second bracket: tensor([1, 2, 3])
Third bracket: 1


In [101]:
x[:, 0]

tensor([[ 1,  2,  3],
        [10, 11, 12]])

In [102]:
x[:, :, 1]

tensor([[ 2,  5,  8],
        [11, 14, 17]])

In [103]:
x[:, 1, 1]

tensor([ 5, 14])

In [104]:
x[0, 0, :]

tensor([1, 2, 3])

### Pytorch tensors and Numpy

In [105]:
import numpy as np

In [110]:
# Numpy to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [111]:
# Tensor to numpy
tensor = torch.ones(7)
array = tensor.numpy()
tensor, array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility

In [113]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(f'Tensor A:\n{random_tensor_A}')
print(f'Tensor B:\n{random_tensor_B}')
print(f'Does Tensor A equal Tensor B?')
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.6401, 0.8823, 0.1259, 0.3054],
        [0.2694, 0.9607, 0.0022, 0.5045],
        [0.9239, 0.8234, 0.7196, 0.4880]])
Tensor B:
tensor([[0.9011, 0.8759, 0.8584, 0.3418],
        [0.5555, 0.3992, 0.0235, 0.8930],
        [0.2409, 0.0920, 0.1770, 0.8702]])
Does Tensor A equal Tensor B?


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [114]:
# Set random seed
random_seed = 42
torch.manual_seed(seed=random_seed)
random_tensor_C = torch.rand(3,4)

# Have to reset seed everytime new rand() is called to maintain same values
torch.manual_seed(seed=random_seed)
random_tensor_D = torch.rand(3,4)

print(f'Tensor C:\n{random_tensor_C}')
print(f'Tensor D:\n{random_tensor_D}')
print(f'Does Tensor C equal Tensor D?')
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Does Tensor C equal Tensor D?


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Running tensors on GPU

In [117]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [119]:
# Putting tensor on GPU (if available)

tensor = torch.rand(3,4)
tensor = tensor.to(device)
tensor.device

device(type='cpu')